// Generated by scripts/generate_touch_profiles.py; edit profiles/*.json.
#pragma once
#include <cstdint>
#include <string_view>
namespace profile {
struct Build {
    const char* version;
    char sha256[65];
    uintptr_t touch_count_slot;
    uintptr_t get_touch_slot;
    uintptr_t touch_supported_slot;
    uintptr_t frame_count_slot;
    uintptr_t screen_width_slot;
    uintptr_t screen_height_slot;
    uintptr_t ui_class_slot;
    uintptr_t static_reference_pool;
    uintptr_t ui_state_offset;
    uintptr_t get_layout_override;
    uintptr_t set_layout_override;
    uintptr_t get_effective_layout;
    uintptr_t class_initialized_offset;
    uintptr_t override_property_offset;
    uintptr_t default_property_offset;
};
inline constexpr Build builds[] = {
    {
        "3.1", "4cba5d52c5fbfd478d2a9ec217075f82216780d56ad1bd1e85e4f724dcce30b4",
        0x540dcb8, // touch_count_slot
        0x540dcd8, // get_touch_slot
        0x540dcc0, // touch_supported_slot
        0x540ad20, // frame_count_slot
        0x5407458, // screen_width_slot
        0x5407460, // screen_height_slot
        0x5450eb0, // ui_class_slot
        0x5360730, // static_reference_pool
        0x2d9c0, // ui_state_offset
        0x15b462a0, // get_layout_override
        0x15b46680, // set_layout_override
        0x15b43570, // get_effective_layout
        0xcb, // class_initialized_offset
        0x80, // override_property_offset
        0x88, // default_property_offset
    },
    {
        "3.2", "2be366e9fca3b02d37e5285764590df6094b4ddc1dfb85ecd2320e326528f834",
        0x4f7efa8, // touch_count_slot
        0x4f7efc8, // get_touch_slot
        0x4f7efb0, // touch_supported_slot
        0x4f7bef0, // frame_count_slot
        0x4f785f8, // screen_width_slot
        0x4f78600, // screen_height_slot
        0x4fc13e0, // ui_class_slot
        0x4ecd400, // static_reference_pool
        0x2e468, // ui_state_offset
        0x134c7d90, // get_layout_override
        0x134c7090, // set_layout_override
        0x134c8150, // get_effective_layout
        0xcb, // class_initialized_offset
        0x98, // override_property_offset
        0x88, // default_property_offset
    },
};
struct Field { const char* name; uintptr_t Build::* value; };
inline constexpr Field fields[] = {
    {"touch_count_slot", &Build::touch_count_slot},
    {"get_touch_slot", &Build::get_touch_slot},
    {"touch_supported_slot", &Build::touch_supported_slot},
    {"frame_count_slot", &Build::frame_count_slot},
    {"screen_width_slot", &Build::screen_width_slot},
    {"screen_height_slot", &Build::screen_height_slot},
    {"ui_class_slot", &Build::ui_class_slot},
    {"static_reference_pool", &Build::static_reference_pool},
    {"ui_state_offset", &Build::ui_state_offset},
    {"get_layout_override", &Build::get_layout_override},
    {"set_layout_override", &Build::set_layout_override},
    {"get_effective_layout", &Build::get_effective_layout},
    {"class_initialized_offset", &Build::class_initialized_offset},
    {"override_property_offset", &Build::override_property_offset},
    {"default_property_offset", &Build::default_property_offset},
};
inline constexpr const Build* find(std::string_view sha256) {
    for (const auto& build : builds) if (sha256 == build.sha256) return &build;
    return nullptr;
}
}
