"""Build native scan rules from the preserved 3.1 sample (Capstone is build-time only).

RIP references, direct branch targets and metadata indices are masked. Layout
rules also mask object displacements; semantic constants and Touch ABI remain
fixed. No target-version addresses or hashes are emitted into the scan rules.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path
import capstone as cs
from capstone.x86_const import X86_OP_MEM, X86_REG_RIP, X86_REG_RSP, X86_REG_RBP
from pe import PE, require

NATIVE_ROOT = Path(__file__).resolve().parents[3]
INCLUDE = NATIVE_ROOT / 'games' / 'zzz' / 'include'
TESTDATA = NATIVE_ROOT / 'games' / 'zzz' / 'testdata'

RULES = [
    ('input_region', 0x19FBF1B30, 592, False),
    ('screen_region', 0x19E60D8A0, 224, False),
    ('frame_region', 0x19E956450, 128, False),
    ('touch_loop', 0x196FE5770, 160, True),
    ('device_selector', 0x1958A87E0, 512, True),
    ('layout_getter', 0x195B462A0, 285, True),
    ('layout_setter', 0x195B46680, 341, True),
    ('effective_layout', 0x195B43570, 183, True),
]

def make_rule(pe, name, va, length, layout):
    decoder = cs.Cs(cs.CS_ARCH_X86, cs.CS_MODE_64)
    decoder.detail = True
    instructions = list(decoder.disasm(pe.read(va, length), va))
    length = instructions[-1].address + instructions[-1].size - va
    data = pe.read(va, length)
    mask = bytearray([255] * length)
    for ins in instructions:
        at = ins.address-va
        if ins.disp_offset and any(op.type == X86_OP_MEM and
                (op.mem.base == X86_REG_RIP or (layout and op.mem.base not in (X86_REG_RSP, X86_REG_RBP))) for op in ins.operands):
            mask[at+ins.disp_offset:at+ins.disp_offset+ins.disp_size] = bytes(ins.disp_size)
        if ins.imm_offset:
            value = int.from_bytes(ins.bytes[ins.imm_offset:ins.imm_offset+ins.imm_size], 'little')
            branch = ins.group(cs.CS_GRP_CALL) or ins.group(cs.CS_GRP_JUMP)
            stack = layout and ins.mnemonic in ('sub', 'add') and ins.op_str.startswith('rsp,')
            if branch or value >= 4096 or stack:
                mask[at+ins.imm_offset:at+ins.imm_offset+ins.imm_size] = bytes(ins.imm_size)
    # Zero masked bytes too, so the production rule does not embed original RVAs.
    pattern = bytes(b & m for b, m in zip(data, mask))
    return pattern, bytes(mask)

def generate(game_assembly):
    pe = PE(game_assembly)
    lines = ['// Generated by games/zzz/tools/generate_scan_patterns.py from explicit 3.1 evidence.',
             '#pragma once', '#include <cstdint>', '#include <span>', '#include "pattern.hpp"',
             'namespace scan_rules {',
             'using Pattern = touchui::binary::Pattern;']
    report = []
    for name, va, length, layout in RULES:
        data, mask = make_rule(pe, name, va, length, layout)
        for suffix, values in (('bytes', data), ('mask', mask)):
            lines += [f'inline constexpr uint8_t {name}_{suffix}[] = {{']
            lines += ['    '+','.join(f'0x{x:02x}' for x in values[i:i+24])+',' for i in range(0, len(values), 24)]
            lines += ['};']
        lines += [f'inline constexpr Pattern {name}{{"{name}", {name}_bytes, {name}_mask}};']
        report.append({'name':name, 'reference_va':hex(va), 'length':len(data),
                       'fixed_bytes':sum(bool(m) for m in mask), 'layout_masking':layout,
                       'pattern_sha256':hashlib.sha256(data+mask).hexdigest()})
    lines += ['}', '']
    return '\n'.join(lines), {'reference_sha256':pe.sha256, 'rules':report}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--game-assembly', type=Path, required=True,
                        help='Explicit preserved 3.1 GameAssembly.dll input')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text, report = generate(args.game_assembly)
    path = INCLUDE/'scan_patterns.hpp'
    evidence = TESTDATA/'patterns.json'
    if args.check:
        assert path.read_text(encoding='utf-8') == text, 'Stale scan_patterns.hpp'
        assert json.loads(evidence.read_text(encoding='utf-8')) == report, 'Stale pattern evidence'
        print('PASS: scan rules match preserved reference evidence')
    else:
        path.write_text(text, encoding='utf-8')
        evidence.parent.mkdir(parents=True, exist_ok=True)
        evidence.write_text(json.dumps(report, indent=2)+'\n', encoding='utf-8')
        print(path)

if __name__ == '__main__':
    main()
